package gorulechecker

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedFileDetection(t *testing.T) {
	path := writeGeneratedTestFile(t, "// Code generated by test; DO NOT EDIT.\npackage sample\n")
	generated, err := isGeneratedFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !generated {
		t.Fatal("generated file was not detected")
	}
}

func TestGeneratedFileRejectsMarkerLikeText(t *testing.T) {
	path := writeGeneratedTestFile(t, "// mentions Code generated but is not a marker; DO NOT EDIT.\npackage sample\n")
	generated, err := isGeneratedFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if generated {
		t.Fatal("ordinary marker-like text was detected as generated")
	}
}

func writeGeneratedTestFile(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "generated.go")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}
