package gorulechecker

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedFileDetection(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	content := "// Code generated by test; DO NOT EDIT.\npackage sample\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	generated, err := isGeneratedFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !generated {
		t.Fatal("generated file was not detected")
	}
}
